### PR TITLE
Use atom-ide-console

### PR DESCRIPTION
**Pull request by richiksc**

### CODE REVIEW

**Comment by richiksc** [comment]
If you decide to merge this as well as #176, please merge #176 first.

**Comment by jas-chen** [comment]
hi @richiksc could u explain what feature is this? looks it uses another console, however it also starts/stops the server via that console?

**Comment by richiksc** [comment]
atom-ide-console is a feature of the package atom-ide-ui, a package endorsed by Atom as "Atom IDE". The console is a pane in the GUI itself and is designed for other packages to hook into. The console also has buttons to start and stop services. My PR hooks into the console provided by Atom IDE and gracefully falls back to the standard console if it is not installed.

**Comment by jas-chen** [comment]
Okay i got it, i'm willing to merge this, could you help to resolve the conflicts?

**Comment by richiksc** [comment]
Yeah, sure. How can I help?

**Comment by richiksc** [comment]
Ok, I can rebase and resolve the conflicts tomorrow

**Comment by richiksc** [comment]
@jas-chen I've resolved the merge conflicts.

**Comment by jas-chen** [comment]
@richiksc i've released it, could u test if it works? thanks!

**Comment by richiksc** [comment]
Sure, I'll test it about 6PM UTC

**Comment by richiksc** [comment]
I was in fact able to test it earlier - It works like a charm, with or without atom-ide-console installed. However, you do need to restart Atom after disabling or enabling atom-ide-console for live-server to work properly.

**Comment by jas-chen** [comment]
Great!

**Pull request merged**
