### PR TITLE
Consume tool-bar

### PR DESCRIPTION
**Pull request by richiksc**
These changes will add a toggle to tool-bar for starting and stopping the server if tool-bar is installed.

tool-bar package: https://atom.io/packages/tool-bar

### CODE REVIEW

**Comment by jas-chen** [comment]
humm... i personally don't think user will start/stop live server frequently, putting a button on the tool bar seems too much for me.

**Comment by richiksc** [comment]
I guess - You would only need to start the live server once when developing, and then stop it at the end of your session. I still like having a button on the toolbar. I'll make it a config option

**Comment by richiksc** [comment]
@jas-chen I made it an optional config option that is turned off by default.

**Comment by richiksc** [comment]
@jas-chen anything else needed to merge this?

**Pull request closed without merging**
