### PR TITLE
Better arg condition and add config option for default port

### PR DESCRIPTION
**Pull request by richiksc**

### CODE REVIEW

**Comment by richiksc** [comment]
@jas-chen ?

**Comment by jas-chen** [comment]
hi @richiksc, sorry for the late reply, providing a UI for users to set the port is a great idea, however this package will have too many ways to set the port, users might confused about which one will be the top priority, and which one will be overwrote, this is my concern, what do you think?

**Comment by richiksc** [comment]
@jas-chen There's three ways to set the port
1) Through keyboard shortcut/command - This overrides everything
2) Through .atom-live-server.json - This overrides config setting and is specific to the project
3) Through config setting - only used when default command is used (`startServer`) and no .atom-live-server.json is found.

**Comment by richiksc** [comment]
@jas-chen will you merge this?

**Comment by richiksc** [comment]
Sorry, deleting this pull request. Will open another one with same changes from different branch.

**Pull request closed without merging**
